# -*- coding: utf-8 -*-
"""PLP_Python_Programming_Assignement 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UFGRKA9SiAFQ9_5p8qo6COw0y6CWHnxL

**Funmilayo Mary Aina**

# **Basic Calculator Program **

Create a simple Python program that asks the user to input two numbers and a mathematical operation (addition, subtraction, multiplication, or division).
Perform the operation based on the user's input and print the result.
Example: If a user inputs 10, 5, and +, your program should display 10 + 5 = 15
"""

col1 =float(input("Enter the first number"))
Col2 =float(input("Enter the second number"))
opt =input("Enter the operator: +, -, *, /")

if opt == "+":
  outpt = col1+ Col2
  print(f"{col1} +{Col2} = {outpt}")

elif opt == "-":
  outpt = col1- Col2
  print(f"{col1} -{Col2} = {outpt}")

elif opt == "*":
  outpt = col1* Col2
  print(f"{col1} *{Col2} = {outpt}")

elif opt == "/":
  outpt = col1/ Col2
  print(f"{col1} /{Col2} = {outpt}")

else:
  print("Invalid operation")





